#!/usr/bin/env bash

set -xeuo pipefail
source ./tools/build_config

# if root is running this script then do not use `sudo` (some distros
# do not supply it)
if [[ "${UID}" == 0 ]]; then
    sudo=''
else
    sudo='sudo'
fi

echo "cloning non-submodule source dependencies"
try_clone_checkout "https://github.com/tgeijten/opensim3-scone.git" "master"
try_clone_checkout "https://github.com/simbody/simbody.git" "Simbody-3.5.4"
try_clone_checkout "https://github.com/create-dmg/create-dmg.git" "v1.0.8"

echo "getting submodule dependencies"
git submodule update --init --recursive
