#!/usr/bin/env bash

set -xeuo pipefail
source "$( dirname ${BASH_SOURCE} )/build_config"

# echo "${0}: starting OpenSceneGraph build"
# ${SCONE_REPOSITORY_DIR}/tools/unix_2a_build-osg

echo "${0}: starting simbody build"
${SCONE_REPOSITORY_DIR}/tools/unix_2b_build-simbody-fix

echo "${0}: starting opensim3 build"
${SCONE_REPOSITORY_DIR}/tools/unix_2c_build-opensim3-fix

echo "${0}: dependency build complete: the following directories were created:"
# find "${OSG_INSTALL_PATH}" -maxdepth 2 -mindepth 1
find "${SIMBODY_INSTALL_PATH}" -maxdepth 2 -mindepth 1
find "${OPENSIM3_INSTALL_PATH}" -maxdepth 2 -mindepth 1

echo "${0}: all dependencies built: building SCONE"
${SCONE_REPOSITORY_DIR}/tools/unix_2d_build-scone-core-hfd

