#!/usr/bin/env bash

set -xeuo pipefail
script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "${script_dir}/build_config"

echo "${0}: building simbody"

mkdir -p "${SIMBODY_INSTALL_PATH}"
mkdir -p simbody/build
cd simbody/build
cmake .. \
      -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" \
      -DCMAKE_VERBOSE_MAKEFILE="${CMAKE_VERBOSE_MAKEFILE}" \
      -DCMAKE_INSTALL_PREFIX="${SIMBODY_INSTALL_PATH}" \
      -DCMAKE_INSTALL_RPATH="\$ORIGIN"

cmake --build . --parallel ${NUM_BUILD_JOBS} --target install
cd -
